### ISSUE TITLE
Error while processing route: index undefined is not a function TypeError: undefined is not a function

### ISSUE THREAD

**Issue by szachara** [luxbet/ember-cli-llama-table#17]
Hi,

and this is the last error, which I have, when I install this addon.
After this addon is installed, i'm getting this error on every route.

Ember 1.11.0, Ember CLI 0.2.2 and ember-cli-llama-table 0.3.10.

This error is at index route and need to tell, that on this route i'm not using ember-cli-llama-table and I don't have any call of `{{llama-table}}` in the index.hbs view.

```
Error while processing route: index undefined is not a function TypeError: undefined is not a function
    at Ember.default.Route.reopen._actions.didTransition (http://localhost:4200/assets/vendor.js:74633:34)
    at Object.triggerEvent (http://localhost:4200/assets/vendor.js:34646:36)
    at trigger (http://localhost:4200/assets/vendor.js:57005:16)
    at finalizeTransition (http://localhost:4200/assets/vendor.js:56014:9)
    at http://localhost:4200/assets/vendor.js:55435:16
    at tryCatch (http://localhost:4200/assets/vendor.js:57447:16)
    at invokeCallback (http://localhost:4200/assets/vendor.js:57459:17)
    at publish (http://localhost:4200/assets/vendor.js:57430:11)
    at http://localhost:4200/assets/vendor.js:37754:7
    at Queue.invoke (http://localhost:4200/assets/vendor.js:11420:18)
```

And this error ( it's the same ), when I call `{{llama-table}}` in the view and have setup controller, like example on the github page, the example is at test route.

```
Error while processing route: test undefined is not a function TypeError: undefined is not a function
    at Ember.default.Route.reopen._actions.didTransition (http://localhost:4200/assets/vendor.js:74633:34)
    at Object.triggerEvent (http://localhost:4200/assets/vendor.js:34646:36)
    at trigger (http://localhost:4200/assets/vendor.js:57005:16)
    at finalizeTransition (http://localhost:4200/assets/vendor.js:56014:9)
    at http://localhost:4200/assets/vendor.js:55435:16
    at tryCatch (http://localhost:4200/assets/vendor.js:57447:16)
    at invokeCallback (http://localhost:4200/assets/vendor.js:57459:17)
    at publish (http://localhost:4200/assets/vendor.js:57430:11)
    at http://localhost:4200/assets/vendor.js:37754:7
    at Queue.invoke (http://localhost:4200/assets/vendor.js:11420:18)
```

If you need more details, let me know.

Thank you.

**Comment by j-** [comment]
Hey Silver, could you possibly publish a test repo on GitHub so I can reproduce and investigate this issue further?

**Comment by szachara** [comment]
Ok, I send link later.

**Comment by szachara** [comment]
Hi,

I have created Github repo at https://github.com/szachara/llama-table-bug--17/tree/bug-%2317, where this bug is reproduced.
The bug is reproduced on branch `bug-#17`.

Pls, read the __Installation__ section and section __How to reproduce this bug__. 
I have tested every point of this sections and everything works as you expect.
